# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0, max_length=11)),
                ('whatsapp', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
            ],
        ),
    ]
